// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Chirp struct {
	ID        int32
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
}

type User struct {
	ID             int32
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
