// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Chirp struct {
	ID        int32
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             int32
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
